image: python:3.6.3
clone:
  depth: full

pipelines:
  default:
    - step:
        name: Deploy to Heroku test server
        script:
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$STG_HEROKU_APP_NAME.git HEAD:master

    - step:
        name: Static Code Analysis
        script:
          - pip install -r requirements.txt
          - pylint --load-plugins pylint_django [..other options..] tasks --disable=missing-docstring
          - pylint --load-plugins pylint_django [..other options..] e2etests --disable=missing-docstring

    - step:
        name: Run tests against test server
        image: adrianashymoniak/python.3.6-selenium-chrome:3.6
        caches:
          - pip
        script:
           - pip install -r requirements.txt
           - echo -e "BASE_URL = '$STG_BASE_URL'\nDB_SETUP = {'database':'$STG_DB_NAME', 'user':'$STG_DB_USER', 'password':'$STG_DB_PASSWORD', 'host':'$STG_DB_HOST', 'port':'$STG_DB_PORT'}\nHEADLESS = True\nAPP_TIME_ZONE = 'Europe/Kiev'\nAUTO_INSTALL_DRIVER = False\n" > e2etests/configs.py
           - mkdir test-reports
           - nosetests --with-xunit -v -m "(tests)|(^test_user_can)" --xunit-file=./test-reports/nose-junit.xml

    - step:
        name: Deploy to Heroku production server
        script:
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$PRODUCTION_HEROKU_APP_NAME.git HEAD:master
