# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.6.3
clone:
  depth: full

pipelines:
  default:
    - step:
        name: Deploy to Heroku test server
        script:
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD

    - step:
        name: Run tests against test server
        image: joyzoursky/python-chromedriver:3.6-selenium
        caches:
          - pip
        script:
           - pip install -r requirements.txt
           - echo -e "BASE_URL = '$TEST_SERVER_BASE_URL'\nDB_SETUP = {'database':'$DB_NAME', 'user':'$DB_USER', 'password':'$DB_PASSWORD', 'host':'$DB_HOST', 'port':'$DB_PORT'}\nHEADLESS = True\nAPP_TIME_ZONE = 'Europe/Kiev'\n" > e2etests/configs.py
           - mkdir test-reports
           - nosetests --with-xunit -v -m "(tests)|(^test_user_can_)" --xunit-file=./test-reports/nose-junit.xml