# Generated by Django 2.0.1 on 2018-02-03 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(blank=True, max_length=150)),
                ('task_description', models.CharField(blank=True, max_length=250)),
                ('time_estimated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('time_published', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('time_edited', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
