# Generated by Django 2.0.1 on 2018-02-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20180211_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_estimated',
            field=models.DateField(null=True),
        ),
    ]
