# Generated by Django 2.0.1 on 2018-03-11 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20180311_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_published',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
