# Generated by Django 2.0.1 on 2018-04-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20180311_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('New', 'new'), ('In progress', 'in progress'), ('Done', 'done')], default=None, max_length=11),
        ),
    ]
