# Generated by Django 2.0.1 on 2018-06-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20180423_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priorities',
            field=models.CharField(blank=True, choices=[('Minor', 'minor'), ('Normal', 'normal'), ('Major', 'major'), ('Critical', 'critical')], max_length=8),
        ),
    ]
